
----------------- REFERENCE TABLES (MASTER TABLES) -----------------
CREATE TABLE "application_status_reference" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "value" VARCHAR(100) NOT NULL,
  "created_on" NUMERIC(13) NOT NULL,
  CONSTRAINT application_status_reference_pk_id PRIMARY KEY("id")
);

CREATE TABLE "gender_reference" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "value" VARCHAR(100) NOT NULL,
  "created_on" NUMERIC(13),
  CONSTRAINT gender_reference_pk_id PRIMARY KEY("id")
);

CREATE TABLE "marital_status_reference" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "value" VARCHAR(100) NOT NULL,
  "created_on" NUMERIC(13),
  CONSTRAINT marital_status_reference_pk_id PRIMARY KEY("id")
);

CREATE TABLE "address_type_reference" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "value" VARCHAR(100) NOT NULL,
  "created_on" NUMERIC(13) NOT NULL,
  CONSTRAINT address_type_reference_pk_id PRIMARY KEY("id")
);

CREATE TABLE "ownership_type_reference" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "value" VARCHAR(100) NOT NULL,
  "created_on" NUMERIC(13) NOT NULL,
  CONSTRAINT ownership_type_reference_pk_id PRIMARY KEY("id")
);

CREATE TABLE "relationship_type_reference" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "value" VARCHAR(100) NOT NULL,
  "created_on" NUMERIC(13) NOT NULL,
  CONSTRAINT relationship_type_reference_pk_id PRIMARY KEY("id")
);

CREATE TABLE "employment_type_reference" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "value" VARCHAR(100) NOT NULL,
  "created_on" NUMERIC(13) NOT NULL,
  CONSTRAINT employment_type_reference_pk_id PRIMARY KEY("id")
);

CREATE TABLE "income_range_reference" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "value" VARCHAR(100) NOT NULL,
  "created_on" NUMERIC(13) NOT NULL,
  CONSTRAINT income_range_reference_pk_id PRIMARY KEY("id")
);

CREATE TABLE "contact_type_reference" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "value" VARCHAR(100) NOT NULL,
  "created_on" NUMERIC(13) NOT NULL,
  CONSTRAINT contact_type_reference_pk_id PRIMARY KEY("id")
);

CREATE TABLE "contact_context_reference" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "value" VARCHAR(100) NOT NULL,
  "created_on" NUMERIC(13) NOT NULL,
  CONSTRAINT contact_context_reference_pk_id PRIMARY KEY("id")
);

CREATE TABLE "auth_type_reference" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "auth_type" VARCHAR(100) NOT NULL,
  "created_on" NUMERIC(13) NOT NULL,
  CONSTRAINT auth_type_reference_pk_id PRIMARY KEY("id")
);

CREATE TABLE "client_types" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "client_type" VARCHAR(50) NOT NULL,
  "created_on" NUMERIC(13) NOT NULL,
  CONSTRAINT client_types_pk_id PRIMARY KEY("id")
);

----------------- DEPENDENT TABLES -----------------

----------------- MAIN TABLE -----------------
CREATE TABLE "application_info" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "application_number" VARCHAR(15) NOT NULL,
  "status" INT4 NOT NULL,
  "comments" VARCHAR,
  "created_on" NUMERIC(13) NOT NULL,
  "updated_on" NUMERIC(13) NOT NULL,
  "created_by" VARCHAR(100) NOT NULL,
  CONSTRAINT application_info_pk_id PRIMARY KEY("id")
);
CREATE INDEX "application_info_id_idx01" ON public."application_info" USING btree (id);
CREATE INDEX "application_info_application_number_idx02" ON public."application_info" USING btree (application_number);

CREATE TABLE "application_product_mapping" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "application_id" INT4 NOT NULL,
  "lead_id" VARCHAR(100),
  "product_id" INT4 NOT NULL,
  "los_product_type" VARCHAR(15) NOT NULL,
  "created_on" NUMERIC(13) NOT NULL,
  "created_by" VARCHAR(100) NOT NULL,
  CONSTRAINT application_product_mapping_pk_id PRIMARY KEY("id")
);
CREATE INDEX "application_product_mapping_application_id_idx01" ON public."application_product_mapping" USING btree (application_id);

CREATE TABLE "workflow_application_info" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "application_id" INT4 NOT NULL,
  "instance_id" VARCHAR(32),
  "business_key" VARCHAR(32),
  "created_on" NUMERIC(13),
  "updated_on" NUMERIC(13),
  CONSTRAINT workflow_application_info_pk_id PRIMARY KEY("id")
);
CREATE INDEX "workflow_application_info_application_id_idx01" ON public."workflow_application_info" USING btree (application_id);

CREATE TABLE "applicant_info" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "application_id" INT4 NOT NULL,
  "first_name" VARCHAR(100) NOT NULL,
  "middle_name" VARCHAR(100),
  "last_name" VARCHAR(100),
  "full_name" VARCHAR(255),
  "gender_id" INT4 NOT NULL,
  "salutation" VARCHAR(10),
  "dob" date NOT NULL,
  "marital_status_id" INT4,
  "created_on" NUMERIC(13) NOT NULL,
  "updated_on" NUMERIC(13) NOT NULL,
  CONSTRAINT applicant_info_pk_id PRIMARY KEY("id")
);
CREATE INDEX "applicant_info_application_id_idx01" ON public."applicant_info" USING btree (application_id);

CREATE TABLE "applicant_address_info" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "application_id" INT4 NOT NULL,
  "address_type_id" INT4 NOT NULL,
  "ownership_type_id" INT4,
  "address" VARCHAR NOT NULL,
  "pincode" NUMERIC(6),
  "landmark" VARCHAR,
  "latitude" NUMERIC(8,6),
  "longitude" NUMERIC(9,6),
  "city" VARCHAR(255),
  "district" VARCHAR(255),
  "state" VARCHAR(255),
  "status" boolean NOT NULL,
  "created_on" NUMERIC(13) NOT NULL,
  "updated_on" NUMERIC(13) NOT NULL,
  "updated_by" VARCHAR(100) NOT NULL,
  CONSTRAINT applicant_address_info_pk_id PRIMARY KEY("id")
);
CREATE INDEX "applicant_address_info_application_id_idx01" ON public."applicant_address_info" USING btree (application_id);

CREATE TABLE "applicant_relationship_info" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "application_id" INT4 NOT NULL,
  "relationship_type_id" INT4 NOT NULL,
  "realtionship_value" VARCHAR(255) NOT NULL,
  "created_on" NUMERIC(13) NOT NULL,
  "updated_on" NUMERIC(13) NOT NULL,
  "updated_by" VARCHAR(100) NOT NULL,
  CONSTRAINT applicant_relationship_info_pk_id PRIMARY KEY("id")
);
CREATE INDEX "applicant_relationship_info_application_id_idx01" ON public."applicant_relationship_info" USING btree (application_id);

CREATE TABLE "application_events" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "application_id" INT4 NOT NULL,
  "event_name" VARCHAR(100) NOT NULL,
  "event_status" VARCHAR(50) NOT NULL,
  "event_value" json NOT NULL,
  "created_on" NUMERIC(13) NOT NULL,
  "triggered_by" VARCHAR(100) NOT NULL,
  CONSTRAINT application_events_pk_id PRIMARY KEY("id")
);
CREATE INDEX "application_events_application_id_idx01" ON public."application_events" USING btree (application_id);

CREATE TABLE "application_change_logs" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "application_id" INT4 NOT NULL,
  "name" VARCHAR(100) NOT NULL,
  "status" VARCHAR(50) NOT NULL,
  "value" json NOT NULL,
  "created_on" NUMERIC(13) NOT NULL,
  "triggered_by" VARCHAR(255) NOT NULL,
  CONSTRAINT application_change_logs_pk_id PRIMARY KEY("id")
);
CREATE INDEX "application_change_logs_application_id_idx01" ON public."application_change_logs" USING btree (application_id);

CREATE TABLE "applicant_employment_info" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "application_id" INT4 NOT NULL,
  "employment_type_id" INT4 NOT NULL,
  "income_range_id" INT4 NULL,
  "company_name" VARCHAR NULL,
  "created_on" NUMERIC(13) NOT NULL,
  "updated_on" NUMERIC(13),
  CONSTRAINT applicant_employment_info_pk_id PRIMARY KEY("id")
);
CREATE INDEX "applicant_employment_info_application_id_idx01" ON public."applicant_employment_info" USING btree (application_id);


CREATE TABLE "applicant_contact_info" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "application_id" INT4 NOT NULL,
  "contact_type_id" INT4 NOT NULL,
  "contact_context_id" INT4,
  "contact_value" VARCHAR(255) NOT NULL,
  "status" boolean NOT NULL,
  "created_on" NUMERIC(13) NOT NULL,
  "updated_on" NUMERIC(13) NOT NULL,
  CONSTRAINT applicant_contact_info_pk_id PRIMARY KEY("id")
);
CREATE INDEX "applicant_contact_info_application_id_idx01" ON public."applicant_contact_info" USING btree (application_id);

CREATE TABLE "consumer_products" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "client_id" INT4 NOT NULL,
  "product_name" VARCHAR(100) NOT NULL,
  "product_code" VARCHAR(15) NOT NULL,
  "workflow_info" json,
  "auth_type_id" INT4 NULL,
  "auth_info" json,
  "created_on" NUMERIC(13) NOT NULL,
  CONSTRAINT consumer_products_pk_id PRIMARY KEY("id")
);

CREATE TABLE "consumer_clients" (
  "id" INT4 GENERATED BY DEFAULT AS IDENTITY,
  "client_name" VARCHAR(100) NOT NULL,
  "client_code" VARCHAR(10) NOT NULL,
  "client_type" INT4 NOT NULL,
  "created_on" NUMERIC(13) NOT NULL,
  CONSTRAINT consumer_clients_pk_id PRIMARY KEY("id")
);


----------------- FOREIGN_KEY RELATIONSHIPS -----------------
ALTER TABLE "application_info" ADD FOREIGN KEY ("status") REFERENCES "application_status_reference" ("id") ON DELETE SET NULL;

ALTER TABLE "application_product_mapping" ADD FOREIGN KEY ("application_id") REFERENCES "application_info" ("id") ON DELETE SET NULL;

ALTER TABLE "workflow_application_info" ADD FOREIGN KEY ("application_id") REFERENCES "application_info" ("id") ON DELETE SET NULL;

ALTER TABLE "applicant_info" ADD FOREIGN KEY ("gender_id") REFERENCES "gender_reference" ("id") ON DELETE SET NULL;

ALTER TABLE "applicant_info" ADD FOREIGN KEY ("application_id") REFERENCES "application_info" ("id") ON DELETE SET NULL;

ALTER TABLE "applicant_info" ADD FOREIGN KEY ("marital_status_id") REFERENCES "marital_status_reference" ("id") ON DELETE SET NULL;

ALTER TABLE "applicant_address_info" ADD FOREIGN KEY ("address_type_id") REFERENCES "address_type_reference" ("id") ON DELETE SET NULL;

ALTER TABLE "applicant_address_info" ADD FOREIGN KEY ("ownership_type_id") REFERENCES "ownership_type_reference" ("id") ON DELETE SET NULL;

ALTER TABLE "applicant_address_info" ADD FOREIGN KEY ("application_id") REFERENCES "application_info" ("id") ON DELETE SET NULL;

ALTER TABLE "applicant_relationship_info" ADD FOREIGN KEY ("application_id") REFERENCES "application_info" ("id") ON DELETE SET NULL;

ALTER TABLE "applicant_relationship_info" ADD FOREIGN KEY ("relationship_type_id") REFERENCES "relationship_type_reference" ("id") ON DELETE SET NULL;

ALTER TABLE "application_events" ADD FOREIGN KEY ("application_id") REFERENCES "application_info" ("id") ON DELETE SET NULL;

ALTER TABLE "application_change_logs" ADD FOREIGN KEY ("application_id") REFERENCES "application_info" ("id") ON DELETE SET NULL;

ALTER TABLE "applicant_employment_info" ADD FOREIGN KEY ("application_id") REFERENCES "application_info" ("id") ON DELETE SET NULL;

ALTER TABLE "applicant_employment_info" ADD FOREIGN KEY ("employment_type_id") REFERENCES "employment_type_reference" ("id") ON DELETE SET NULL;

ALTER TABLE "applicant_employment_info" ADD FOREIGN KEY ("income_range_id") REFERENCES "income_range_reference" ("id") ON DELETE SET NULL;

ALTER TABLE "applicant_contact_info" ADD FOREIGN KEY ("application_id") REFERENCES "application_info" ("id") ON DELETE SET NULL;

ALTER TABLE "applicant_contact_info" ADD FOREIGN KEY ("contact_type_id") REFERENCES "contact_type_reference" ("id") ON DELETE SET NULL;

ALTER TABLE "applicant_contact_info" ADD FOREIGN KEY ("contact_context_id") REFERENCES "contact_context_reference" ("id") ON DELETE SET NULL;

ALTER TABLE "application_product_mapping" ADD FOREIGN KEY ("product_id") REFERENCES "consumer_products" ("id") ON DELETE SET NULL;

ALTER TABLE "consumer_products" ADD FOREIGN KEY ("auth_type_id") REFERENCES "auth_type_reference" ("id") ON DELETE SET NULL;

ALTER TABLE "consumer_products" ADD FOREIGN KEY ("client_id") REFERENCES "consumer_clients" ("id") ON DELETE SET NULL;

ALTER TABLE "consumer_clients" ADD FOREIGN KEY ("client_type") REFERENCES "client_types" ("id") ON DELETE SET NULL;




----------------- DROP TABLE COMMANDS ----------------
--DROP TABLE "applicant_contact_info";
--DROP TABLE "applicant_employment_info";
--DROP TABLE "application_change_logs";
--DROP TABLE "application_events";
--DROP TABLE "applicant_relationship_info";
--DROP TABLE "applicant_address_info";
--DROP TABLE "applicant_info";
--DROP TABLE "workflow_application_info";
--DROP TABLE "application_product_mapping";
--DROP TABLE "application_info";
--DROP TABLE "consumer_products";
--DROP TABLE "consumer_clients";
--DROP TABLE "client_types";
--DROP TABLE "auth_type_reference";
--DROP TABLE "contact_context_reference";
--DROP TABLE "contact_type_reference";
--DROP TABLE "income_range_reference";
--DROP TABLE "employment_type_reference";
--DROP TABLE "relationship_type_reference";
--DROP TABLE "ownership_type_reference";
--DROP TABLE "address_type_reference";
--DROP TABLE "marital_status_reference";
--DROP TABLE "gender_reference";
--DROP TABLE "application_status_reference";